CREATE TABLE IF NOT EXISTS CITY_AREA (
    AREA_CODE VARCHAR(30) PRIMARY KEY,
    AREA_NAME VARCHAR(200) NOT NULL UNIQUE,

    LATITUDE NUMERIC(10, 7),
    LONGTITUDE NUMERIC(10, 7),

    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE CITY_AREA
IS '서울 실시간 도시데이터에서 제공하는 주요 장소 기준정보';

COMMENT ON COLUMN CITY_AREA.AREA_CODE
IS '서울 실시간 도시데이터 장소 코드';

COMMENT ON COLUMN CITY_AREA.AREA_NAME 
IS '서울 실시간 도시데이터 장소명';

COMMENT ON COLUMN CITY_AREA.LATITUDE
IS '장소 대표 위도';

COMMENT ON COLUMN CITY_AREA.LONGTITUDE
IS '장소 대표 경도';

COMMENT ON COLUMN CITY_AREA.IS_ACTIVE
IS 'API 수집 대상 여부';